name: Run

on:
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn --production --frozen-lockfile

      - name: Start script
        env:
          ACKEE_ENDPOINT: ${{ secrets.ACKEE_ENDPOINT }}
          ACKEE_EVENT_ID: ${{ secrets.ACKEE_EVENT_ID }}
          URL: ${{ secrets.URL }}
        run: yarn start
